// -----------------------------------------------------------------------
//  * File: event.c
//      Library responsible for handling system events generated by
//      push buttons and serial communication, including protocol parsing.
//
//  * Authors:
//      Eduardo Castro
//      Glauber Moura
//
//  * Year: 2025/2026
// -----------------------------------------------------------------------

#include "peripherics.h"
#include "event.h"
#include "serial.h"

static unsigned char key_ant;
static char protocol_msg[16];
static uint8_t protocol_index;
static char protocol_flag;


/**
 * This function initializes the event handling module. It configures the
 * push buttons, resets the previous key state and clears all protocol-related
 * control variables. After this initialization, the system is ready to
 * generate events based on user interaction or incoming serial data.
 */
void eventInit(void) {
    configureButtons();
    key_ant = 0;
    protocol_flag = 0;
    protocol_index = 0;

}


/**
 * This function reads and processes all possible event sources in the system.
 * Events may originate from push button interactions or from characters
 * received through the serial interface. Button events are detected by
 * comparing the current key state with the previous one, while serial data
 * can either generate direct events or be interpreted as part of a protocol
 * message delimited by specific start and end characters.
 *
 * When a complete protocol message is detected, the function returns a
 * protocol-specific event and makes the received message available through
 * an auxiliary access function.
 */
unsigned int eventRead(void) {

    char key, data;
    unsigned int ev = EV_NOEVENT;

    key = readButtons();

    if (key != key_ant) ev = key;

    data = readSerial();

    if(data != '[' && !protocol_flag){
        if (data == 'r') ev = EV_RIGHT;
        if (data == 'l') ev =  EV_LEFT;
        if (data == 's') ev = EV_ENTER;
        if (data == 'u') ev =    EV_UP;
        if (data == 'd') ev =  EV_DOWN;
    }

    else {

        protocol_flag = 1;
        if(data == ']'){
            protocol_flag = 0;
            protocol_msg[protocol_index] = '\0';
            protocol_index = 0;
            return EV_PROTOCOL;
        }

        else if(data!='['){
            if (data != '\n' && data != '\0' && data != '\t') {
                if (protocol_index < sizeof(protocol_msg) - 1) {
                    protocol_msg[protocol_index++] = data;
                }
            }
        }
    }

    key_ant = key;
    return ev;
}


/**
 * This function returns a pointer to the last protocol message received
 * through the serial interface. The message is stored internally by the
 * event handling module and is updated whenever a complete protocol frame
 * is detected.
 */
char *getProtocolMSG(){return protocol_msg;}
