// -----------------------------------------------------------------------
//  * File: main.c
//
//  * Project overview:
//      Embedded application based on the LPC11xx microcontroller, structured
//      around a finite state machine. The system integrates multiple
//      peripherals such as LCD, UART, GPIO buttons, LEDs, ADC and an external
//      RTC via I2C.
//
//      The application provides a menu-driven interface displayed on an LCD,
//      allowing the user to configure time, date, alarm thresholds, language
//      and timing parameters through push buttons or serial commands.
//      A state machine coordinates the behavior of the system, while events
//      are generated by user inputs and peripheral interactions.
//
//      This file contains the main entry point of the system, responsible for
//      initializing all hardware modules, libraries and software layers, and
//      for running the main loop that continuously executes the state machine.
//
//  * Authors:
//      Eduardo Castro
//      Glauber Moura
//
//  * Year: 2025/2026
// -----------------------------------------------------------------------


#include "LCD.h"
#include "clocks.h"
#include "serial.h"
#include "LED.h"
#include "event.h"
#include "var.h"
#include "stateMachine.h"
#include "output.h"
#include "adc.h"
#include "i2cRtc.h"


int main(void)
{

    // libs init
    clocksConfig();
    configureLED();
    turnOffLEDs();
    configureSerial();
    I2CConfig();
    LCDpinConfig();
    outputInit();
    eventInit();
    varInit();
    smInit();
    ADCconfig();
    ADCpinConfig(0);


    for (;;) {
        //state machine:
        smLoop();
    }
    return 0;
}
